// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/grpc/proto/robot.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RobotControl_SendCommand_FullMethodName       = "/robot.v1.RobotControl/SendCommand"
	RobotControl_SetMode_FullMethodName           = "/robot.v1.RobotControl/SetMode"
	RobotControl_GetMode_FullMethodName           = "/robot.v1.RobotControl/GetMode"
	RobotControl_SetMessage_FullMethodName        = "/robot.v1.RobotControl/SetMessage"
	RobotControl_HasPendingMessage_FullMethodName = "/robot.v1.RobotControl/HasPendingMessage"
	RobotControl_TakeMessage_FullMethodName       = "/robot.v1.RobotControl/TakeMessage"
	RobotControl_StreamTelemetry_FullMethodName   = "/robot.v1.RobotControl/StreamTelemetry"
)

// RobotControlClient is the client API for RobotControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ====================== Сервис ======================
type RobotControlClient interface {
	// Управление (unary)
	SendCommand(ctx context.Context, in *ControlCommand, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Режим
	SetMode(ctx context.Context, in *SetModeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetMode(ctx context.Context, in *GetModeRequest, opts ...grpc.CallOption) (*GetModeResponse, error)
	// Текстовое сообщение (одно, перезаписывается)
	SetMessage(ctx context.Context, in *SetMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HasPendingMessage(ctx context.Context, in *HasPendingMessageRequest, opts ...grpc.CallOption) (*HasPendingMessageResponse, error)
	TakeMessage(ctx context.Context, in *TakeMessageRequest, opts ...grpc.CallOption) (*TakeMessageResponse, error)
	// Постоянный поток телеметрии (Pi → WSL)
	// WSL открывает один раз и постоянно получает данные
	StreamTelemetry(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Telemetry], error)
}

type robotControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotControlClient(cc grpc.ClientConnInterface) RobotControlClient {
	return &robotControlClient{cc}
}

func (c *robotControlClient) SendCommand(ctx context.Context, in *ControlCommand, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RobotControl_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotControlClient) SetMode(ctx context.Context, in *SetModeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RobotControl_SetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotControlClient) GetMode(ctx context.Context, in *GetModeRequest, opts ...grpc.CallOption) (*GetModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModeResponse)
	err := c.cc.Invoke(ctx, RobotControl_GetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotControlClient) SetMessage(ctx context.Context, in *SetMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RobotControl_SetMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotControlClient) HasPendingMessage(ctx context.Context, in *HasPendingMessageRequest, opts ...grpc.CallOption) (*HasPendingMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasPendingMessageResponse)
	err := c.cc.Invoke(ctx, RobotControl_HasPendingMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotControlClient) TakeMessage(ctx context.Context, in *TakeMessageRequest, opts ...grpc.CallOption) (*TakeMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeMessageResponse)
	err := c.cc.Invoke(ctx, RobotControl_TakeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotControlClient) StreamTelemetry(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Telemetry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RobotControl_ServiceDesc.Streams[0], RobotControl_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Telemetry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotControl_StreamTelemetryClient = grpc.ServerStreamingClient[Telemetry]

// RobotControlServer is the server API for RobotControl service.
// All implementations must embed UnimplementedRobotControlServer
// for forward compatibility.
//
// ====================== Сервис ======================
type RobotControlServer interface {
	// Управление (unary)
	SendCommand(context.Context, *ControlCommand) (*emptypb.Empty, error)
	// Режим
	SetMode(context.Context, *SetModeRequest) (*emptypb.Empty, error)
	GetMode(context.Context, *GetModeRequest) (*GetModeResponse, error)
	// Текстовое сообщение (одно, перезаписывается)
	SetMessage(context.Context, *SetMessageRequest) (*emptypb.Empty, error)
	HasPendingMessage(context.Context, *HasPendingMessageRequest) (*HasPendingMessageResponse, error)
	TakeMessage(context.Context, *TakeMessageRequest) (*TakeMessageResponse, error)
	// Постоянный поток телеметрии (Pi → WSL)
	// WSL открывает один раз и постоянно получает данные
	StreamTelemetry(*emptypb.Empty, grpc.ServerStreamingServer[Telemetry]) error
	mustEmbedUnimplementedRobotControlServer()
}

// UnimplementedRobotControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobotControlServer struct{}

func (UnimplementedRobotControlServer) SendCommand(context.Context, *ControlCommand) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedRobotControlServer) SetMode(context.Context, *SetModeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMode not implemented")
}
func (UnimplementedRobotControlServer) GetMode(context.Context, *GetModeRequest) (*GetModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMode not implemented")
}
func (UnimplementedRobotControlServer) SetMessage(context.Context, *SetMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMessage not implemented")
}
func (UnimplementedRobotControlServer) HasPendingMessage(context.Context, *HasPendingMessageRequest) (*HasPendingMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasPendingMessage not implemented")
}
func (UnimplementedRobotControlServer) TakeMessage(context.Context, *TakeMessageRequest) (*TakeMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TakeMessage not implemented")
}
func (UnimplementedRobotControlServer) StreamTelemetry(*emptypb.Empty, grpc.ServerStreamingServer[Telemetry]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedRobotControlServer) mustEmbedUnimplementedRobotControlServer() {}
func (UnimplementedRobotControlServer) testEmbeddedByValue()                      {}

// UnsafeRobotControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotControlServer will
// result in compilation errors.
type UnsafeRobotControlServer interface {
	mustEmbedUnimplementedRobotControlServer()
}

func RegisterRobotControlServer(s grpc.ServiceRegistrar, srv RobotControlServer) {
	// If the following call panics, it indicates UnimplementedRobotControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RobotControl_ServiceDesc, srv)
}

func _RobotControl_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotControlServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotControl_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotControlServer).SendCommand(ctx, req.(*ControlCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotControl_SetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotControlServer).SetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotControl_SetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotControlServer).SetMode(ctx, req.(*SetModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotControl_GetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotControlServer).GetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotControl_GetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotControlServer).GetMode(ctx, req.(*GetModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotControl_SetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotControlServer).SetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotControl_SetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotControlServer).SetMessage(ctx, req.(*SetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotControl_HasPendingMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasPendingMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotControlServer).HasPendingMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotControl_HasPendingMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotControlServer).HasPendingMessage(ctx, req.(*HasPendingMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotControl_TakeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotControlServer).TakeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotControl_TakeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotControlServer).TakeMessage(ctx, req.(*TakeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotControl_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RobotControlServer).StreamTelemetry(m, &grpc.GenericServerStream[emptypb.Empty, Telemetry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotControl_StreamTelemetryServer = grpc.ServerStreamingServer[Telemetry]

// RobotControl_ServiceDesc is the grpc.ServiceDesc for RobotControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RobotControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "robot.v1.RobotControl",
	HandlerType: (*RobotControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _RobotControl_SendCommand_Handler,
		},
		{
			MethodName: "SetMode",
			Handler:    _RobotControl_SetMode_Handler,
		},
		{
			MethodName: "GetMode",
			Handler:    _RobotControl_GetMode_Handler,
		},
		{
			MethodName: "SetMessage",
			Handler:    _RobotControl_SetMessage_Handler,
		},
		{
			MethodName: "HasPendingMessage",
			Handler:    _RobotControl_HasPendingMessage_Handler,
		},
		{
			MethodName: "TakeMessage",
			Handler:    _RobotControl_TakeMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _RobotControl_StreamTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/grpc/proto/robot.proto",
}
