// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/grpc/proto/robot.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RobotControl_StreamControl_FullMethodName   = "/robot.v1.RobotControl/StreamControl"
	RobotControl_WebRTCSignaling_FullMethodName = "/robot.v1.RobotControl/WebRTCSignaling"
)

// RobotControlClient is the client API for RobotControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RobotControlClient interface {
	StreamControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Command, Telemetry], error)
	// Отдельный стрим для WebRTC signaling (SDP + ICE)
	WebRTCSignaling(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebRTCSignal, WebRTCSignal], error)
}

type robotControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotControlClient(cc grpc.ClientConnInterface) RobotControlClient {
	return &robotControlClient{cc}
}

func (c *robotControlClient) StreamControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Command, Telemetry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RobotControl_ServiceDesc.Streams[0], RobotControl_StreamControl_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Command, Telemetry]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotControl_StreamControlClient = grpc.BidiStreamingClient[Command, Telemetry]

func (c *robotControlClient) WebRTCSignaling(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebRTCSignal, WebRTCSignal], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RobotControl_ServiceDesc.Streams[1], RobotControl_WebRTCSignaling_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WebRTCSignal, WebRTCSignal]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotControl_WebRTCSignalingClient = grpc.BidiStreamingClient[WebRTCSignal, WebRTCSignal]

// RobotControlServer is the server API for RobotControl service.
// All implementations must embed UnimplementedRobotControlServer
// for forward compatibility.
type RobotControlServer interface {
	StreamControl(grpc.BidiStreamingServer[Command, Telemetry]) error
	// Отдельный стрим для WebRTC signaling (SDP + ICE)
	WebRTCSignaling(grpc.BidiStreamingServer[WebRTCSignal, WebRTCSignal]) error
	mustEmbedUnimplementedRobotControlServer()
}

// UnimplementedRobotControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobotControlServer struct{}

func (UnimplementedRobotControlServer) StreamControl(grpc.BidiStreamingServer[Command, Telemetry]) error {
	return status.Error(codes.Unimplemented, "method StreamControl not implemented")
}
func (UnimplementedRobotControlServer) WebRTCSignaling(grpc.BidiStreamingServer[WebRTCSignal, WebRTCSignal]) error {
	return status.Error(codes.Unimplemented, "method WebRTCSignaling not implemented")
}
func (UnimplementedRobotControlServer) mustEmbedUnimplementedRobotControlServer() {}
func (UnimplementedRobotControlServer) testEmbeddedByValue()                      {}

// UnsafeRobotControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotControlServer will
// result in compilation errors.
type UnsafeRobotControlServer interface {
	mustEmbedUnimplementedRobotControlServer()
}

func RegisterRobotControlServer(s grpc.ServiceRegistrar, srv RobotControlServer) {
	// If the following call panics, it indicates UnimplementedRobotControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RobotControl_ServiceDesc, srv)
}

func _RobotControl_StreamControl_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RobotControlServer).StreamControl(&grpc.GenericServerStream[Command, Telemetry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotControl_StreamControlServer = grpc.BidiStreamingServer[Command, Telemetry]

func _RobotControl_WebRTCSignaling_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RobotControlServer).WebRTCSignaling(&grpc.GenericServerStream[WebRTCSignal, WebRTCSignal]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotControl_WebRTCSignalingServer = grpc.BidiStreamingServer[WebRTCSignal, WebRTCSignal]

// RobotControl_ServiceDesc is the grpc.ServiceDesc for RobotControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RobotControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "robot.v1.RobotControl",
	HandlerType: (*RobotControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamControl",
			Handler:       _RobotControl_StreamControl_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WebRTCSignaling",
			Handler:       _RobotControl_WebRTCSignaling_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/grpc/proto/robot.proto",
}
