// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/grpc/proto/robot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====================== Режим работы ======================
type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	Mode_MODE_MANUAL      Mode = 1 // Управление только с Windows
	Mode_MODE_AUTO        Mode = 2 // Управление с WSL (Orchestrator)
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_MANUAL",
		2: "MODE_AUTO",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_MANUAL":      1,
		"MODE_AUTO":        2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_robot_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_robot_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_robot_proto_rawDescGZIP(), []int{0}
}

type SetModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          Mode                   `protobuf:"varint,1,opt,name=mode,proto3,enum=robot.v1.Mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModeRequest) Reset() {
	*x = SetModeRequest{}
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModeRequest) ProtoMessage() {}

func (x *SetModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModeRequest.ProtoReflect.Descriptor instead.
func (*SetModeRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_robot_proto_rawDescGZIP(), []int{0}
}

func (x *SetModeRequest) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

type GetModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModeRequest) Reset() {
	*x = GetModeRequest{}
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModeRequest) ProtoMessage() {}

func (x *GetModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModeRequest.ProtoReflect.Descriptor instead.
func (*GetModeRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_robot_proto_rawDescGZIP(), []int{1}
}

type GetModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          Mode                   `protobuf:"varint,1,opt,name=mode,proto3,enum=robot.v1.Mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModeResponse) Reset() {
	*x = GetModeResponse{}
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModeResponse) ProtoMessage() {}

func (x *GetModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModeResponse.ProtoReflect.Descriptor instead.
func (*GetModeResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_robot_proto_rawDescGZIP(), []int{2}
}

func (x *GetModeResponse) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

// ====================== Команда управления (unary) ======================
type ControlCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steering      float32                `protobuf:"fixed32,1,opt,name=steering,proto3" json:"steering,omitempty"` // -1.0 .. +1.0
	Move          float32                `protobuf:"fixed32,2,opt,name=move,proto3" json:"move,omitempty"`         // -1.0 .. +1.0
	Pan           float32                `protobuf:"fixed32,3,opt,name=pan,proto3" json:"pan,omitempty"`           // -1.0 .. +1.0
	Tilt          float32                `protobuf:"fixed32,4,opt,name=tilt,proto3" json:"tilt,omitempty"`         // -1.0 .. +1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlCommand) Reset() {
	*x = ControlCommand{}
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCommand) ProtoMessage() {}

func (x *ControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCommand.ProtoReflect.Descriptor instead.
func (*ControlCommand) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_robot_proto_rawDescGZIP(), []int{3}
}

func (x *ControlCommand) GetSteering() float32 {
	if x != nil {
		return x.Steering
	}
	return 0
}

func (x *ControlCommand) GetMove() float32 {
	if x != nil {
		return x.Move
	}
	return 0
}

func (x *ControlCommand) GetPan() float32 {
	if x != nil {
		return x.Pan
	}
	return 0
}

func (x *ControlCommand) GetTilt() float32 {
	if x != nil {
		return x.Tilt
	}
	return 0
}

// ====================== Текстовое сообщение (задача для Orchestrator) ======================
type SetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMessageRequest) Reset() {
	*x = SetMessageRequest{}
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMessageRequest) ProtoMessage() {}

func (x *SetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMessageRequest.ProtoReflect.Descriptor instead.
func (*SetMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_robot_proto_rawDescGZIP(), []int{4}
}

func (x *SetMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type HasPendingMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPendingMessageRequest) Reset() {
	*x = HasPendingMessageRequest{}
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPendingMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPendingMessageRequest) ProtoMessage() {}

func (x *HasPendingMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPendingMessageRequest.ProtoReflect.Descriptor instead.
func (*HasPendingMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_robot_proto_rawDescGZIP(), []int{5}
}

type HasPendingMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasMessage    bool                   `protobuf:"varint,1,opt,name=has_message,json=hasMessage,proto3" json:"has_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPendingMessageResponse) Reset() {
	*x = HasPendingMessageResponse{}
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPendingMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPendingMessageResponse) ProtoMessage() {}

func (x *HasPendingMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPendingMessageResponse.ProtoReflect.Descriptor instead.
func (*HasPendingMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_robot_proto_rawDescGZIP(), []int{6}
}

func (x *HasPendingMessageResponse) GetHasMessage() bool {
	if x != nil {
		return x.HasMessage
	}
	return false
}

type TakeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeMessageRequest) Reset() {
	*x = TakeMessageRequest{}
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeMessageRequest) ProtoMessage() {}

func (x *TakeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeMessageRequest.ProtoReflect.Descriptor instead.
func (*TakeMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_robot_proto_rawDescGZIP(), []int{7}
}

type TakeMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeMessageResponse) Reset() {
	*x = TakeMessageResponse{}
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeMessageResponse) ProtoMessage() {}

func (x *TakeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeMessageResponse.ProtoReflect.Descriptor instead.
func (*TakeMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_robot_proto_rawDescGZIP(), []int{8}
}

func (x *TakeMessageResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ====================== Телеметрия (пока оставляем для совместимости) ======================
type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      float32                `protobuf:"fixed32,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Steering      float32                `protobuf:"fixed32,2,opt,name=steering,proto3" json:"steering,omitempty"`
	Pan           float32                `protobuf:"fixed32,3,opt,name=pan,proto3" json:"pan,omitempty"`
	Tilt          float32                `protobuf:"fixed32,4,opt,name=tilt,proto3" json:"tilt,omitempty"`
	MotorA        float32                `protobuf:"fixed32,5,opt,name=motor_a,json=motorA,proto3" json:"motor_a,omitempty"`
	MotorB        float32                `protobuf:"fixed32,6,opt,name=motor_b,json=motorB,proto3" json:"motor_b,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AccelX        float32                `protobuf:"fixed32,8,opt,name=accel_x,json=accelX,proto3" json:"accel_x,omitempty"`
	AccelY        float32                `protobuf:"fixed32,9,opt,name=accel_y,json=accelY,proto3" json:"accel_y,omitempty"`
	AccelZ        float32                `protobuf:"fixed32,10,opt,name=accel_z,json=accelZ,proto3" json:"accel_z,omitempty"`
	GyroX         float32                `protobuf:"fixed32,11,opt,name=gyro_x,json=gyroX,proto3" json:"gyro_x,omitempty"`
	GyroY         float32                `protobuf:"fixed32,12,opt,name=gyro_y,json=gyroY,proto3" json:"gyro_y,omitempty"`
	GyroZ         float32                `protobuf:"fixed32,13,opt,name=gyro_z,json=gyroZ,proto3" json:"gyro_z,omitempty"`
	MotorATarget  float32                `protobuf:"fixed32,14,opt,name=motor_a_target,json=motorATarget,proto3" json:"motor_a_target,omitempty"`
	MotorBTarget  float32                `protobuf:"fixed32,15,opt,name=motor_b_target,json=motorBTarget,proto3" json:"motor_b_target,omitempty"`
	MotorADuty    float32                `protobuf:"fixed32,16,opt,name=motor_a_duty,json=motorADuty,proto3" json:"motor_a_duty,omitempty"`
	MotorBDuty    float32                `protobuf:"fixed32,17,opt,name=motor_b_duty,json=motorBDuty,proto3" json:"motor_b_duty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_robot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_robot_proto_rawDescGZIP(), []int{9}
}

func (x *Telemetry) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Telemetry) GetSteering() float32 {
	if x != nil {
		return x.Steering
	}
	return 0
}

func (x *Telemetry) GetPan() float32 {
	if x != nil {
		return x.Pan
	}
	return 0
}

func (x *Telemetry) GetTilt() float32 {
	if x != nil {
		return x.Tilt
	}
	return 0
}

func (x *Telemetry) GetMotorA() float32 {
	if x != nil {
		return x.MotorA
	}
	return 0
}

func (x *Telemetry) GetMotorB() float32 {
	if x != nil {
		return x.MotorB
	}
	return 0
}

func (x *Telemetry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Telemetry) GetAccelX() float32 {
	if x != nil {
		return x.AccelX
	}
	return 0
}

func (x *Telemetry) GetAccelY() float32 {
	if x != nil {
		return x.AccelY
	}
	return 0
}

func (x *Telemetry) GetAccelZ() float32 {
	if x != nil {
		return x.AccelZ
	}
	return 0
}

func (x *Telemetry) GetGyroX() float32 {
	if x != nil {
		return x.GyroX
	}
	return 0
}

func (x *Telemetry) GetGyroY() float32 {
	if x != nil {
		return x.GyroY
	}
	return 0
}

func (x *Telemetry) GetGyroZ() float32 {
	if x != nil {
		return x.GyroZ
	}
	return 0
}

func (x *Telemetry) GetMotorATarget() float32 {
	if x != nil {
		return x.MotorATarget
	}
	return 0
}

func (x *Telemetry) GetMotorBTarget() float32 {
	if x != nil {
		return x.MotorBTarget
	}
	return 0
}

func (x *Telemetry) GetMotorADuty() float32 {
	if x != nil {
		return x.MotorADuty
	}
	return 0
}

func (x *Telemetry) GetMotorBDuty() float32 {
	if x != nil {
		return x.MotorBDuty
	}
	return 0
}

var File_internal_grpc_proto_robot_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_robot_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/grpc/proto/robot.proto\x12\brobot.v1\x1a\x1bgoogle/protobuf/empty.proto\"4\n" +
	"\x0eSetModeRequest\x12\"\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x0e.robot.v1.ModeR\x04mode\"\x10\n" +
	"\x0eGetModeRequest\"5\n" +
	"\x0fGetModeResponse\x12\"\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x0e.robot.v1.ModeR\x04mode\"f\n" +
	"\x0eControlCommand\x12\x1a\n" +
	"\bsteering\x18\x01 \x01(\x02R\bsteering\x12\x12\n" +
	"\x04move\x18\x02 \x01(\x02R\x04move\x12\x10\n" +
	"\x03pan\x18\x03 \x01(\x02R\x03pan\x12\x12\n" +
	"\x04tilt\x18\x04 \x01(\x02R\x04tilt\"'\n" +
	"\x11SetMessageRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1a\n" +
	"\x18HasPendingMessageRequest\"<\n" +
	"\x19HasPendingMessageResponse\x12\x1f\n" +
	"\vhas_message\x18\x01 \x01(\bR\n" +
	"hasMessage\"\x14\n" +
	"\x12TakeMessageRequest\")\n" +
	"\x13TakeMessageResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xd9\x03\n" +
	"\tTelemetry\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x02R\bdistance\x12\x1a\n" +
	"\bsteering\x18\x02 \x01(\x02R\bsteering\x12\x10\n" +
	"\x03pan\x18\x03 \x01(\x02R\x03pan\x12\x12\n" +
	"\x04tilt\x18\x04 \x01(\x02R\x04tilt\x12\x17\n" +
	"\amotor_a\x18\x05 \x01(\x02R\x06motorA\x12\x17\n" +
	"\amotor_b\x18\x06 \x01(\x02R\x06motorB\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x17\n" +
	"\aaccel_x\x18\b \x01(\x02R\x06accelX\x12\x17\n" +
	"\aaccel_y\x18\t \x01(\x02R\x06accelY\x12\x17\n" +
	"\aaccel_z\x18\n" +
	" \x01(\x02R\x06accelZ\x12\x15\n" +
	"\x06gyro_x\x18\v \x01(\x02R\x05gyroX\x12\x15\n" +
	"\x06gyro_y\x18\f \x01(\x02R\x05gyroY\x12\x15\n" +
	"\x06gyro_z\x18\r \x01(\x02R\x05gyroZ\x12$\n" +
	"\x0emotor_a_target\x18\x0e \x01(\x02R\fmotorATarget\x12$\n" +
	"\x0emotor_b_target\x18\x0f \x01(\x02R\fmotorBTarget\x12 \n" +
	"\fmotor_a_duty\x18\x10 \x01(\x02R\n" +
	"motorADuty\x12 \n" +
	"\fmotor_b_duty\x18\x11 \x01(\x02R\n" +
	"motorBDuty*<\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vMODE_MANUAL\x10\x01\x12\r\n" +
	"\tMODE_AUTO\x10\x022\xfb\x03\n" +
	"\fRobotControl\x12?\n" +
	"\vSendCommand\x12\x18.robot.v1.ControlCommand\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\aSetMode\x12\x18.robot.v1.SetModeRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\aGetMode\x12\x18.robot.v1.GetModeRequest\x1a\x19.robot.v1.GetModeResponse\x12A\n" +
	"\n" +
	"SetMessage\x12\x1b.robot.v1.SetMessageRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x11HasPendingMessage\x12\".robot.v1.HasPendingMessageRequest\x1a#.robot.v1.HasPendingMessageResponse\x12J\n" +
	"\vTakeMessage\x12\x1c.robot.v1.TakeMessageRequest\x1a\x1d.robot.v1.TakeMessageResponse\x12@\n" +
	"\x0fStreamTelemetry\x12\x16.google.protobuf.Empty\x1a\x13.robot.v1.Telemetry0\x01B\"Z robot-server/internal/grpc/pb;pbb\x06proto3"

var (
	file_internal_grpc_proto_robot_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_robot_proto_rawDescData []byte
)

func file_internal_grpc_proto_robot_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_robot_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_robot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_robot_proto_rawDesc), len(file_internal_grpc_proto_robot_proto_rawDesc)))
	})
	return file_internal_grpc_proto_robot_proto_rawDescData
}

var file_internal_grpc_proto_robot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_grpc_proto_robot_proto_goTypes = []any{
	(Mode)(0),                         // 0: robot.v1.Mode
	(*SetModeRequest)(nil),            // 1: robot.v1.SetModeRequest
	(*GetModeRequest)(nil),            // 2: robot.v1.GetModeRequest
	(*GetModeResponse)(nil),           // 3: robot.v1.GetModeResponse
	(*ControlCommand)(nil),            // 4: robot.v1.ControlCommand
	(*SetMessageRequest)(nil),         // 5: robot.v1.SetMessageRequest
	(*HasPendingMessageRequest)(nil),  // 6: robot.v1.HasPendingMessageRequest
	(*HasPendingMessageResponse)(nil), // 7: robot.v1.HasPendingMessageResponse
	(*TakeMessageRequest)(nil),        // 8: robot.v1.TakeMessageRequest
	(*TakeMessageResponse)(nil),       // 9: robot.v1.TakeMessageResponse
	(*Telemetry)(nil),                 // 10: robot.v1.Telemetry
	(*emptypb.Empty)(nil),             // 11: google.protobuf.Empty
}
var file_internal_grpc_proto_robot_proto_depIdxs = []int32{
	0,  // 0: robot.v1.SetModeRequest.mode:type_name -> robot.v1.Mode
	0,  // 1: robot.v1.GetModeResponse.mode:type_name -> robot.v1.Mode
	4,  // 2: robot.v1.RobotControl.SendCommand:input_type -> robot.v1.ControlCommand
	1,  // 3: robot.v1.RobotControl.SetMode:input_type -> robot.v1.SetModeRequest
	2,  // 4: robot.v1.RobotControl.GetMode:input_type -> robot.v1.GetModeRequest
	5,  // 5: robot.v1.RobotControl.SetMessage:input_type -> robot.v1.SetMessageRequest
	6,  // 6: robot.v1.RobotControl.HasPendingMessage:input_type -> robot.v1.HasPendingMessageRequest
	8,  // 7: robot.v1.RobotControl.TakeMessage:input_type -> robot.v1.TakeMessageRequest
	11, // 8: robot.v1.RobotControl.StreamTelemetry:input_type -> google.protobuf.Empty
	11, // 9: robot.v1.RobotControl.SendCommand:output_type -> google.protobuf.Empty
	11, // 10: robot.v1.RobotControl.SetMode:output_type -> google.protobuf.Empty
	3,  // 11: robot.v1.RobotControl.GetMode:output_type -> robot.v1.GetModeResponse
	11, // 12: robot.v1.RobotControl.SetMessage:output_type -> google.protobuf.Empty
	7,  // 13: robot.v1.RobotControl.HasPendingMessage:output_type -> robot.v1.HasPendingMessageResponse
	9,  // 14: robot.v1.RobotControl.TakeMessage:output_type -> robot.v1.TakeMessageResponse
	10, // 15: robot.v1.RobotControl.StreamTelemetry:output_type -> robot.v1.Telemetry
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_robot_proto_init() }
func file_internal_grpc_proto_robot_proto_init() {
	if File_internal_grpc_proto_robot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_robot_proto_rawDesc), len(file_internal_grpc_proto_robot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_robot_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_robot_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_robot_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_robot_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_robot_proto = out.File
	file_internal_grpc_proto_robot_proto_goTypes = nil
	file_internal_grpc_proto_robot_proto_depIdxs = nil
}
