// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/robot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steering      float32                `protobuf:"fixed32,1,opt,name=steering,proto3" json:"steering,omitempty"`
	Pan           float32                `protobuf:"fixed32,2,opt,name=pan,proto3" json:"pan,omitempty"`
	Tilt          float32                `protobuf:"fixed32,3,opt,name=tilt,proto3" json:"tilt,omitempty"`
	Move          float32                `protobuf:"fixed32,4,opt,name=move,proto3" json:"move,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_robot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetSteering() float32 {
	if x != nil {
		return x.Steering
	}
	return 0
}

func (x *Command) GetPan() float32 {
	if x != nil {
		return x.Pan
	}
	return 0
}

func (x *Command) GetTilt() float32 {
	if x != nil {
		return x.Tilt
	}
	return 0
}

func (x *Command) GetMove() float32 {
	if x != nil {
		return x.Move
	}
	return 0
}

type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      float32                `protobuf:"fixed32,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Steering      float32                `protobuf:"fixed32,2,opt,name=steering,proto3" json:"steering,omitempty"`
	Pan           float32                `protobuf:"fixed32,3,opt,name=pan,proto3" json:"pan,omitempty"`
	Tilt          float32                `protobuf:"fixed32,4,opt,name=tilt,proto3" json:"tilt,omitempty"`
	MotorA        float32                `protobuf:"fixed32,5,opt,name=motor_a,json=motorA,proto3" json:"motor_a,omitempty"`
	MotorB        float32                `protobuf:"fixed32,6,opt,name=motor_b,json=motorB,proto3" json:"motor_b,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_proto_robot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{1}
}

func (x *Telemetry) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Telemetry) GetSteering() float32 {
	if x != nil {
		return x.Steering
	}
	return 0
}

func (x *Telemetry) GetPan() float32 {
	if x != nil {
		return x.Pan
	}
	return 0
}

func (x *Telemetry) GetTilt() float32 {
	if x != nil {
		return x.Tilt
	}
	return 0
}

func (x *Telemetry) GetMotorA() float32 {
	if x != nil {
		return x.MotorA
	}
	return 0
}

func (x *Telemetry) GetMotorB() float32 {
	if x != nil {
		return x.MotorB
	}
	return 0
}

func (x *Telemetry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_robot_proto protoreflect.FileDescriptor

const file_proto_robot_proto_rawDesc = "" +
	"\n" +
	"\x11proto/robot.proto\x12\brobot.v1\"_\n" +
	"\aCommand\x12\x1a\n" +
	"\bsteering\x18\x01 \x01(\x02R\bsteering\x12\x10\n" +
	"\x03pan\x18\x02 \x01(\x02R\x03pan\x12\x12\n" +
	"\x04tilt\x18\x03 \x01(\x02R\x04tilt\x12\x12\n" +
	"\x04move\x18\x04 \x01(\x02R\x04move\"\xb9\x01\n" +
	"\tTelemetry\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x02R\bdistance\x12\x1a\n" +
	"\bsteering\x18\x02 \x01(\x02R\bsteering\x12\x10\n" +
	"\x03pan\x18\x03 \x01(\x02R\x03pan\x12\x12\n" +
	"\x04tilt\x18\x04 \x01(\x02R\x04tilt\x12\x17\n" +
	"\amotor_a\x18\x05 \x01(\x02R\x06motorA\x12\x17\n" +
	"\amotor_b\x18\x06 \x01(\x02R\x06motorB\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp2K\n" +
	"\fRobotControl\x12;\n" +
	"\rStreamControl\x12\x11.robot.v1.Command\x1a\x13.robot.v1.Telemetry(\x010\x01B\x14Z\x12robot-client/pb;pbb\x06proto3"

var (
	file_proto_robot_proto_rawDescOnce sync.Once
	file_proto_robot_proto_rawDescData []byte
)

func file_proto_robot_proto_rawDescGZIP() []byte {
	file_proto_robot_proto_rawDescOnce.Do(func() {
		file_proto_robot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_robot_proto_rawDesc), len(file_proto_robot_proto_rawDesc)))
	})
	return file_proto_robot_proto_rawDescData
}

var file_proto_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_robot_proto_goTypes = []any{
	(*Command)(nil),   // 0: robot.v1.Command
	(*Telemetry)(nil), // 1: robot.v1.Telemetry
}
var file_proto_robot_proto_depIdxs = []int32{
	0, // 0: robot.v1.RobotControl.StreamControl:input_type -> robot.v1.Command
	1, // 1: robot.v1.RobotControl.StreamControl:output_type -> robot.v1.Telemetry
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_robot_proto_init() }
func file_proto_robot_proto_init() {
	if File_proto_robot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_robot_proto_rawDesc), len(file_proto_robot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_robot_proto_goTypes,
		DependencyIndexes: file_proto_robot_proto_depIdxs,
		MessageInfos:      file_proto_robot_proto_msgTypes,
	}.Build()
	File_proto_robot_proto = out.File
	file_proto_robot_proto_goTypes = nil
	file_proto_robot_proto_depIdxs = nil
}
